services:
  the-shelf:
    image: ghcr.io/adorablebrillo/the-shelf:latest
    container_name: the-shelf
    ports:
      - "8787:8787"
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /mnt/user/appdata/the-shelf/config:/config
      - /mnt/user/appdata/the-shelf/data:/app/pipeline/data
    restart: unless-stopped
